# Generated by Django 2.2.16 on 2023-04-17 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfoodgram',
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='userfoodgram',
            name='email',
            field=models.EmailField(
                max_length=254,
                unique=True,
                verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userfoodgram',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userfoodgram',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='userfoodgram',
            name='password',
            field=models.CharField(max_length=150, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userfoodgram',
            name='username',
            field=models.CharField(
                error_messages={
                    'unique': 'Пользователь с таким именем уже существует.'},
                help_text='Не более 150 символов. Только буквы, цифры и @/./+/-/_.',
                max_length=150,
                unique=True,
                verbose_name='username'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='following',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Автор')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='follower',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(
                fields=('user', 'author'), name='unique_followers'),
        ),
    ]
